name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5.0.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v2.1.0

  release-msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v5.0.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v2.1.0

  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.0

      - name: Install requirements
        run: |
          sudo apt-get install -y doxygen
          pip3 install -r docs/requirements.txt

      - name: Build documentation with Sphinx
        run: sphinx-build -b html docs build/html -W --keep-going
