name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0

      - name: Install LLVM and Ninja
        run: sudo apt install llvm ninja-build

      - name: Configure CMake
        run: cmake . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja

      - name: Build targets
        run: cmake --build build
