name: build
on:
  workflow_dispatch:
  push:
    branches: ['**']
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: brew install ninja

      - name: Configure CMake
        run: cmake . -G Ninja -B build

      - name: Build targets
        run: cmake --build build

  test:
    runs-on: macos-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          brew install ninja
          pip3 install gcovr

      - name: Configure CMake
        run: cmake . -B build -G Ninja -D BUILD_TESTING=ON

      - name: Build targets
        run: cmake --build build

      - name: Run tests
        run: ctest --verbose --test-dir build --no-compress-output -T Test || true

      - name: Send test result to Testspace
        run: |
          curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-darwin.tgz | tar -zxvf- -C build
          build/testspace config url ${{ secrets.TESTSPACE_URL }}
          build/testspace config project ${{ secrets.TESTSPACE_PROJECT }}
          build/testspace config space ${{ github.ref_name }}
          build/testspace [Tests]"build/Testing/*/Test.xml"

      - name: Generate code coverage info and send to Coveralls
        working-directory: build
        run: |
          gcovr -r .. --exclude-directories _deps --coveralls coverage.json
          curl -v -F json_file=@coverage.json https://coveralls.io/api/v1/jobs
