name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.1

      - name: Configure and build this project
        uses: threeal/cmake-action@v2.0.0

  release-msvc:
    runs-on: windows-2022
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.1

      - name: Configure and build this project
        uses: threeal/cmake-action@v2.0.0

  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.1

      - name: Install requirements
        run: |
          sudo apt-get install -y doxygen
          pip3 install -r docs/requirements.txt

      - name: Build documentation with Sphinx
        run: sphinx-build -b html docs build/html -W --keep-going

      - name: Upload documentation as artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: html
          path: build/html
