name: build
on:
  workflow_dispatch:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure CMake
        run: cmake . -B build -G Ninja

      - name: Build targets
        run: cmake --build build

  release-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Install Ninja
        run: choco install -y ninja

      - name: Configure CMake
        run: cmake . -B build -G Ninja

      - name: Build targets
        run: cmake --build build
