name: test
on:
  workflow_dispatch:
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.0.0
        with:
          generator: Ninja
          cxx-compiler: clang++
          args: -DBUILD_TESTING=ON

      - name: Run unit tests
        id: run_tests
        run: ctest --verbose --test-dir build --no-compress-output -T Test

      - name: Setup Testspace client
        id: setup_testspace
        if: steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'
        uses: testspace-com/setup-testspace@v1.0.5
        with:
          domain: ${{github.repository_owner}}

      - name: Send test result to Testspace
        if: steps.setup_testspace.outcome == 'success'
        run: testspace [Tests]"build/Testing/*/Test.xml"

      - name: Install LLVM
        run: sudo apt install llvm

      - name: Generate and send code coverage report to Coveralls
        if: steps.run_tests.outcome == 'success' || steps.run_tests.outcome == 'failure'
        uses: threeal/gcovr-action@v0.1.0
        with:
          gcov-executable: llvm-cov gcov
          exclude: build/*
          coveralls-send: true
          coveralls-repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}

  check-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.0.0
        with:
          generator: Ninja
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON

  check-warning-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.0.0
        with:
          cxx-compiler: cl
          cxx-flags: /WX
          args: -DBUILD_TESTING=ON

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.2.0

      - name: Install cmake-format
        run: pip3 install cmake-format

      - name: Configure and check formatting
        uses: threeal/cmake-action@v1.0.0
        with:
          targets: format check-format
