name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.2

      - name: Configure and build this project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: RESULT_ENABLE_TESTS=ON

      - name: Test this project
        uses: threeal/ctest-action@v1.1.0

      - name: Check coverage
        uses: threeal/gcovr-action@v1.1.0
        with:
          excludes: build/*
          fail-under-line: 99

  check-formatting:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.2.2

      - name: Configure and check formatting
        uses: threeal/cmake-action@v2.1.0
        with:
          build-args: --target format --target check-format
