name: test
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Configure, build, and test this project
        id: cmake_action
        uses: threeal/cmake-action@v1.2.0
        with:
          generator: Ninja
          cxx-compiler: clang++
          args: -DBUILD_TESTING=ON
          run-test: true
          test-args: --no-compress-output -T Test

      - name: Setup Testspace client
        id: setup_testspace
        if: steps.cmake_action.outcome == 'success' || steps.cmake_action.outcome == 'failure'
        uses: testspace-com/setup-testspace@v1.0.6
        with:
          domain: ${{github.repository_owner}}

      - name: Send test result to Testspace
        if: steps.setup_testspace.outcome == 'success'
        run: testspace [Tests]"build/Testing/*/Test.xml"

      - name: Generate and send code coverage report to Coveralls
        if: steps.cmake_action.outcome == 'success' || steps.cmake_action.outcome == 'failure'
        uses: threeal/gcovr-action@v0.2.0
        with:
          gcov-executable: llvm-cov gcov
          exclude: build/*
          coveralls-send: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  check-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.2.0
        with:
          generator: Ninja
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON
          run-build: true

  check-warning-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.2.0
        with:
          cxx-compiler: cl
          cxx-flags: /WX
          args: -DBUILD_TESTING=ON
          run-build: true

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Configure and check formatting
        uses: threeal/cmake-action@v1.2.0
        with:
          run-build: true
          build-args: --target format --target check-format
