name: test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.4

      - name: Configure, build, and test this project
        id: cmake_action
        uses: threeal/cmake-action@v1.3.0
        with:
          args: -DBUILD_TESTING=ON
          run-test: true

      - name: Check coverage
        uses: threeal/gcovr-action@v1.0.0
        with:
          excludes: build/*
          fail-under-line: 99

  check-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.4

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.3.0
        with:
          cxx-flags: -Werror
          args: -DBUILD_TESTING=ON
          run-build: true

  check-warning-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.4

      - name: Configure and build this project
        uses: threeal/cmake-action@v1.3.0
        with:
          cxx-flags: /WX
          args: -DBUILD_TESTING=ON
          run-build: true

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4.1.4

      - name: Configure and check formatting
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          build-args: --target format --target check-format
